### ISSUE TITLE
How to start the program and what mouse/microphone should we use?

### ISSUE THREAD

**Issue by BiEchi** [Alex-Lian/ECE385_final_project#1]
Dear Programmers Xinyu LIAN and Tianyu LIU,
  We're group taking ECE385 from ZJUI-2019. I'm Hao BAI and my partner is Junyan LI. After consulting professor Zuofu CHENG, we decide to do something on implementing algorithms on the DE2-115 board to accelerate computation. After research, we finally decide to go on with your project. Here are some questions after our kick-off meeting:
1. How can we play around with the demo? We cannot find the documentation for demo.
2. How can we use the mouse to control the board? Just connection?
3. What device should we equip the board with, in order to demo? We've found that a VGA screen and a keyboard is required. How about the mouse and MIDI microphone? Moreover, how can we use them?

We're sincerely waiting for your response and we hope to make this project gaining further power.

Thanks!

**Comment by xylian86** [comment]
Hi, Hao. We are glad you can improve our work and happy to solve your questions.

> How can we play around with the demo? We cannot find the documentation for demo.

Unfortunately, we do not prepare the guide for the demo. But I believe as long as you connect correctly, you can run it.

> How can we use the mouse to control the board? Just connection?

Please see the annotation in the code file.

> What device should we equip the board with, in order to demo? We've found that a VGA screen and a keyboard is required. How about the mouse and MIDI microphone? Moreover, how can we use them?

VGA screen, keyboard, mouse and cable sound are all the four devices we used.  Btw, I added the block diagram to the [readme](https://github.com/Alex-Lian/shortest-path-search-on-FGPA/blob/master/README.md), which may help you to understand it.

**Comment by xylian86** [comment]
Close this Issue as there are no additional questions.
